# Generated by Django 3.0.1 on 2020-01-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('nick_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('abbr', models.CharField(max_length=150)),
                ('nba_stats_team_id', models.IntegerField()),
                ('alt_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
