# Generated by Django 3.0.1 on 2020-01-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0003_auto_20200103_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMiscData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('off_rtg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('def_rtg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('net_rtg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pace', models.DecimalField(decimal_places=1, max_digits=7)),
                ('ft_rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('three_att_rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('true_shooting_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('off_efg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('off_tov_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('off_orb_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('off_ft_per_fga', models.DecimalField(decimal_places=3, max_digits=7)),
                ('def_efg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('def_tov_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('def_orb_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('def_ft_per_fga', models.DecimalField(decimal_places=3, max_digits=7)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdata.Team')),
            ],
        ),
    ]
