# Generated by Django 3.0.1 on 2020-01-10 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0005_auto_20200104_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamShooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_2_pt_fga', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pct_0_3_ft_fga', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pct_3_10_ft_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_10_16_ft_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_16_3pt_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_3pt_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('_2_pt_fg_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('_0_3_ft_fg_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('_3_10_ft_fg_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('_10_16_ft_fg_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('_16_3pt_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('_3pt_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_astd_2_pt_fg', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pct_dunks_att', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pct_layups_att', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_corner_3_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('_corner_3_fg_pct', models.DecimalField(decimal_places=3, max_digits=7)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdata.Team')),
            ],
        ),
    ]
