# Generated by Django 3.0.1 on 2020-01-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0006_teamshooting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_0_3_ft_fg_pct',
            new_name='m_0_3_ft_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_10_16_ft_fg_pct',
            new_name='m_10_16_ft_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_16_3pt_fg_pct',
            new_name='m_16_3pt_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_2_pt_fg_pct',
            new_name='m_2_pt_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_3_10_ft_fg_pct',
            new_name='m_3_10_ft_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_3pt_fg_pct',
            new_name='m_3pt_fg_pct',
        ),
        migrations.RenameField(
            model_name='teamshooting',
            old_name='_corner_3_fg_pct',
            new_name='m_corner_3_fg_pct',
        ),
    ]
