# Generated by Django 3.0.1 on 2020-01-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0007_auto_20200109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamshooting',
            name='m_0_3_ft_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='m_10_16_ft_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='m_2_pt_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='m_3_10_ft_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='m_corner_3_fg_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='pct_0_3_ft_fga',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='pct_2_pt_fga',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='pct_astd_2_pt_fg',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='pct_dunks_att',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
