# Generated by Django 3.0.1 on 2020-01-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0008_auto_20200109_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamshooting',
            name='morey_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=7),
        ),
    ]
