# Generated by Django 3.0.1 on 2020-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0009_teamshooting_morey_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='East', max_length=150),
            preserve_default=False,
        ),
    ]
