# Generated by Django 3.0.1 on 2020-01-15 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0010_team_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammiscdata',
            name='def_efg',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='def_ft_per_fga',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='ft_rate',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='off_efg',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='off_ft_per_fga',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='three_att_rate',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='true_shooting_pct',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
        migrations.CreateModel(
            name='DefensiveShooting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morey_rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('pct_2_pt_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_0_3_ft_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_3_10_ft_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_10_16_ft_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_16_3pt_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_3pt_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_2_pt_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_0_3_ft_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_3_10_ft_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_10_16_ft_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_16_3pt_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_3pt_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_astd_2_pt_fg', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_dunks_att', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_layups_att', models.DecimalField(decimal_places=1, max_digits=7)),
                ('pct_corner_3_fga', models.DecimalField(decimal_places=1, max_digits=7)),
                ('m_corner_3_fg_pct', models.DecimalField(decimal_places=1, max_digits=7)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamdata.Team')),
            ],
        ),
    ]
