# Generated by Django 3.0.1 on 2020-01-15 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamdata', '0011_auto_20200114_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensiveshooting',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_team_name', to='teamdata.Team'),
        ),
        migrations.AlterField(
            model_name='teammiscdata',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_team_name', to='teamdata.Team'),
        ),
        migrations.AlterField(
            model_name='teamshooting',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_team_name', to='teamdata.Team'),
        ),
    ]
